# Generated by Django 3.0.5 on 2020-04-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='species',
        ),
    ]
